/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    roles: Role;
    'size-metrics': SizeMetric;
    problems: Problem;
    solutions: Solution;
    assets: Asset;
    'composite-assets': CompositeAsset;
    'calculation-models': CalculationModel;
    benchmarks: Benchmark;
    'proof-findings': ProofFinding;
    'cta-rules': CtaRule;
    experiments: Experiment;
    'design-variants': DesignVariant;
    'copy-keys': CopyKey;
    leads: Lead;
    'lead-events': LeadEvent;
    'consent-records': ConsentRecord;
    pages: Page;
    settings: Setting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'size-metrics': SizeMetricsSelect<false> | SizeMetricsSelect<true>;
    problems: ProblemsSelect<false> | ProblemsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    'composite-assets': CompositeAssetsSelect<false> | CompositeAssetsSelect<true>;
    'calculation-models': CalculationModelsSelect<false> | CalculationModelsSelect<true>;
    benchmarks: BenchmarksSelect<false> | BenchmarksSelect<true>;
    'proof-findings': ProofFindingsSelect<false> | ProofFindingsSelect<true>;
    'cta-rules': CtaRulesSelect<false> | CtaRulesSelect<true>;
    experiments: ExperimentsSelect<false> | ExperimentsSelect<true>;
    'design-variants': DesignVariantsSelect<false> | DesignVariantsSelect<true>;
    'copy-keys': CopyKeysSelect<false> | CopyKeysSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'lead-events': LeadEventsSelect<false> | LeadEventsSelect<true>;
    'consent-records': ConsentRecordsSelect<false> | ConsentRecordsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  slug: string;
  label: string;
  sizeMetric: number | SizeMetric;
  endAusgang: 'gespraech' | 'partnerprogramm' | 'nur-loesungen' | 'vermarktungsprozess' | 'projektprozess';
  allowMandatsCTA?: boolean | null;
  sizeIndependent?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "size-metrics".
 */
export interface SizeMetric {
  id: number;
  name: string;
  slug: string;
  frageWortlaut: string;
  buckets: {
    label: string;
    rank: number;
    unitsMid?: number | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problems".
 */
export interface Problem {
  id: number;
  title: string;
  slug: string;
  userFacingDescription: string;
  roleFilters?: (number | Role)[] | null;
  sizeMetricFilters?: (number | SizeMetric)[] | null;
  valueCategory?: ('ertrag' | 'effizienz' | 'risiko')[] | null;
  solutions: (number | Solution)[];
  defaultSolutionOrder?: (number | Solution)[] | null;
  calculationModel?: (number | null) | CalculationModel;
  priority: 'P1' | 'P2' | 'P3';
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  slug: string;
  shortDescription: string;
  helpsWhen?: string | null;
  relatedProblems?: (number | Problem)[] | null;
  assets?: (number | Asset)[] | null;
  primaryAsset?: (number | null) | Asset;
  calculationModel?: (number | null) | CalculationModel;
  valueCategory: 'ertrag' | 'effizienz' | 'risiko';
  nutzenAussage?: string | null;
  scalabilityLevel?: number | null;
  scaleBreakNote: string;
  urgencyTextKey?: string | null;
  ctaRules?: (number | CtaRule)[] | null;
  privacyWarning?: string | null;
  legalWarning?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: number;
  title: string;
  slug: string;
  assetType: 'prompt' | 'video' | 'guide' | 'checklist' | 'image' | 'example' | 'warning' | 'template' | 'composite';
  summary: string;
  contentBlocks?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  childAssets?: (number | Asset)[] | null;
  copyable?: boolean | null;
  source?: string | null;
  accessLevel?: ('public' | 'gated') | null;
  riskLevel?: ('niedrig' | 'mittel' | 'hoch') | null;
  qualityStatus: 'draft' | 'reviewed' | 'approved';
  requiresLegalReview?: boolean | null;
  requiresPrivacyNote?: boolean | null;
  lastReviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculation-models".
 */
export interface CalculationModel {
  id: number;
  modelId: string;
  name: string;
  valueCategory: 'ertrag' | 'effizienz' | 'risiko';
  requiredInputs?:
    | {
        key: string;
        id?: string | null;
      }[]
    | null;
  optionalInputs?:
    | {
        key: string;
        id?: string | null;
      }[]
    | null;
  benchmarkFactors?: (number | Benchmark)[] | null;
  formula: 'M1' | 'M2' | 'M3' | 'M4';
  explanationText: string;
  sourceNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benchmarks".
 */
export interface Benchmark {
  id: number;
  key: string;
  min: number;
  max: number;
  unit: string;
  source: string;
  isPlaceholder?: boolean | null;
  lastVerifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-rules".
 */
export interface CtaRule {
  id: number;
  name: string;
  roleFilters?: (number | Role)[] | null;
  problemFilters?: (number | Problem)[] | null;
  solutionFilters?: (number | Solution)[] | null;
  minSizeScore?: number | null;
  maxSizeScore?: number | null;
  minRelevanceScore?: number | null;
  allowRisiko?: boolean | null;
  primaryLabel: string;
  sublineKey?: string | null;
  secondaryLabel?: string | null;
  destination: 'gespraech' | 'partnerprogramm' | 'pdf' | 'loesung';
  priority?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "composite-assets".
 */
export interface CompositeAsset {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  parts: (number | Asset)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-findings".
 */
export interface ProofFinding {
  id: number;
  date: string;
  source: string;
  category: 'ertrag' | 'risiko' | 'struktur' | 'effizienz';
  title: string;
  affectedCount?: number | null;
  baseCount?: number | null;
  valueMin?: number | null;
  valueMax?: number | null;
  calculationNote?: string | null;
  status: 'identifiziert' | 'umsetzung-gestartet' | 'realisiert';
  realizedValue?: number | null;
  evidenceRef?: string | null;
  publicApproved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiments".
 */
export interface Experiment {
  id: number;
  name: string;
  hypothesis?: string | null;
  variants: {
    id: string;
    weight?: number | null;
  }[];
  trafficAllocation?: number | null;
  targetAudience?: string | null;
  successMetric?: 'booking_confirmed' | null;
  startDate?: string | null;
  endDate?: string | null;
  status?: ('draft' | 'running' | 'paused' | 'done') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-variants".
 */
export interface DesignVariant {
  id: number;
  name: string;
  slug: 'emerald-premium' | 'trust-blue' | 'neutral-editorial';
  tokens?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "copy-keys".
 */
export interface CopyKey {
  id: number;
  key: string;
  value: string;
  version?: number | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  phone?: string | null;
  source: string;
  utmSource?: string | null;
  utmCampaign?: string | null;
  landingPage?: string | null;
  role?: string | null;
  sizeBucket?: string | null;
  relevantUnits?: number | null;
  salesPerYear?: number | null;
  projectsPerYear?: number | null;
  mandateCount?: number | null;
  selectedProblem?: string | null;
  displayedSolutions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  openedSolutions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  copiedAssets?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  shownValueRanges?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  relevanceScore?: number | null;
  leadScore?: number | null;
  diySignal?: boolean | null;
  ctaClicked?: string | null;
  calendarBookingId?: string | null;
  consentRecords?: (number | ConsentRecord)[] | null;
  leadStatus?: ('neu' | 'kontaktiert' | 'gespraech' | 'assessment' | 'partnerschaft' | 'kalt') | null;
  notes?: string | null;
  gespraechseinstieg?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records".
 */
export interface ConsentRecord {
  id: number;
  type: 'pdf' | 'newsletter' | 'contact' | 'calendar';
  accepted: boolean;
  timestamp: string;
  textVersion: string;
  source?: string | null;
  lead?: (number | null) | Lead;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-events".
 */
export interface LeadEvent {
  id: number;
  lead: number | Lead;
  type: string;
  timestamp: string;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  metaDescription?: string | null;
  ogTitle?: string | null;
  ogImage?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  label: string;
  thresholdHigh: {
    buyAndHold: number;
    hausverwaltung: number;
    makler: number;
    projektentwickler: number;
  };
  scoreWeights: {
    w1Size: number;
    w2Value: number;
    w3RoleFit: number;
  };
  monthlySlots?: number | null;
  scarcityTrue?: boolean | null;
  privacyflowReady?: boolean | null;
  proofBandEnabled?: boolean | null;
  calComUrl?: string | null;
  partnerprogrammLink?: string | null;
  stundensatzDefault?: {
    min?: number | null;
    max?: number | null;
  };
  brevoListId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'size-metrics';
        value: number | SizeMetric;
      } | null)
    | ({
        relationTo: 'problems';
        value: number | Problem;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'assets';
        value: number | Asset;
      } | null)
    | ({
        relationTo: 'composite-assets';
        value: number | CompositeAsset;
      } | null)
    | ({
        relationTo: 'calculation-models';
        value: number | CalculationModel;
      } | null)
    | ({
        relationTo: 'benchmarks';
        value: number | Benchmark;
      } | null)
    | ({
        relationTo: 'proof-findings';
        value: number | ProofFinding;
      } | null)
    | ({
        relationTo: 'cta-rules';
        value: number | CtaRule;
      } | null)
    | ({
        relationTo: 'experiments';
        value: number | Experiment;
      } | null)
    | ({
        relationTo: 'design-variants';
        value: number | DesignVariant;
      } | null)
    | ({
        relationTo: 'copy-keys';
        value: number | CopyKey;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'lead-events';
        value: number | LeadEvent;
      } | null)
    | ({
        relationTo: 'consent-records';
        value: number | ConsentRecord;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'settings';
        value: number | Setting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  sizeMetric?: T;
  endAusgang?: T;
  allowMandatsCTA?: T;
  sizeIndependent?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "size-metrics_select".
 */
export interface SizeMetricsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  frageWortlaut?: T;
  buckets?:
    | T
    | {
        label?: T;
        rank?: T;
        unitsMid?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problems_select".
 */
export interface ProblemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  userFacingDescription?: T;
  roleFilters?: T;
  sizeMetricFilters?: T;
  valueCategory?: T;
  solutions?: T;
  defaultSolutionOrder?: T;
  calculationModel?: T;
  priority?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  helpsWhen?: T;
  relatedProblems?: T;
  assets?: T;
  primaryAsset?: T;
  calculationModel?: T;
  valueCategory?: T;
  nutzenAussage?: T;
  scalabilityLevel?: T;
  scaleBreakNote?: T;
  urgencyTextKey?: T;
  ctaRules?: T;
  privacyWarning?: T;
  legalWarning?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  assetType?: T;
  summary?: T;
  contentBlocks?: T;
  childAssets?: T;
  copyable?: T;
  source?: T;
  accessLevel?: T;
  riskLevel?: T;
  qualityStatus?: T;
  requiresLegalReview?: T;
  requiresPrivacyNote?: T;
  lastReviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "composite-assets_select".
 */
export interface CompositeAssetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  parts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculation-models_select".
 */
export interface CalculationModelsSelect<T extends boolean = true> {
  modelId?: T;
  name?: T;
  valueCategory?: T;
  requiredInputs?:
    | T
    | {
        key?: T;
        id?: T;
      };
  optionalInputs?:
    | T
    | {
        key?: T;
        id?: T;
      };
  benchmarkFactors?: T;
  formula?: T;
  explanationText?: T;
  sourceNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "benchmarks_select".
 */
export interface BenchmarksSelect<T extends boolean = true> {
  key?: T;
  min?: T;
  max?: T;
  unit?: T;
  source?: T;
  isPlaceholder?: T;
  lastVerifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proof-findings_select".
 */
export interface ProofFindingsSelect<T extends boolean = true> {
  date?: T;
  source?: T;
  category?: T;
  title?: T;
  affectedCount?: T;
  baseCount?: T;
  valueMin?: T;
  valueMax?: T;
  calculationNote?: T;
  status?: T;
  realizedValue?: T;
  evidenceRef?: T;
  publicApproved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-rules_select".
 */
export interface CtaRulesSelect<T extends boolean = true> {
  name?: T;
  roleFilters?: T;
  problemFilters?: T;
  solutionFilters?: T;
  minSizeScore?: T;
  maxSizeScore?: T;
  minRelevanceScore?: T;
  allowRisiko?: T;
  primaryLabel?: T;
  sublineKey?: T;
  secondaryLabel?: T;
  destination?: T;
  priority?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiments_select".
 */
export interface ExperimentsSelect<T extends boolean = true> {
  name?: T;
  hypothesis?: T;
  variants?:
    | T
    | {
        id?: T;
        weight?: T;
      };
  trafficAllocation?: T;
  targetAudience?: T;
  successMetric?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-variants_select".
 */
export interface DesignVariantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tokens?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "copy-keys_select".
 */
export interface CopyKeysSelect<T extends boolean = true> {
  key?: T;
  value?: T;
  version?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  phone?: T;
  source?: T;
  utmSource?: T;
  utmCampaign?: T;
  landingPage?: T;
  role?: T;
  sizeBucket?: T;
  relevantUnits?: T;
  salesPerYear?: T;
  projectsPerYear?: T;
  mandateCount?: T;
  selectedProblem?: T;
  displayedSolutions?: T;
  openedSolutions?: T;
  copiedAssets?: T;
  shownValueRanges?: T;
  relevanceScore?: T;
  leadScore?: T;
  diySignal?: T;
  ctaClicked?: T;
  calendarBookingId?: T;
  consentRecords?: T;
  leadStatus?: T;
  notes?: T;
  gespraechseinstieg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-events_select".
 */
export interface LeadEventsSelect<T extends boolean = true> {
  lead?: T;
  type?: T;
  timestamp?: T;
  data?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consent-records_select".
 */
export interface ConsentRecordsSelect<T extends boolean = true> {
  type?: T;
  accepted?: T;
  timestamp?: T;
  textVersion?: T;
  source?: T;
  lead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  metaDescription?: T;
  ogTitle?: T;
  ogImage?: T;
  body?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  label?: T;
  thresholdHigh?:
    | T
    | {
        buyAndHold?: T;
        hausverwaltung?: T;
        makler?: T;
        projektentwickler?: T;
      };
  scoreWeights?:
    | T
    | {
        w1Size?: T;
        w2Value?: T;
        w3RoleFit?: T;
      };
  monthlySlots?: T;
  scarcityTrue?: T;
  privacyflowReady?: T;
  proofBandEnabled?: T;
  calComUrl?: T;
  partnerprogrammLink?: T;
  stundensatzDefault?:
    | T
    | {
        min?: T;
        max?: T;
      };
  brevoListId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}