export * from './spanne';
export * from './schmerzBereich';
export * from './phase';
export * from './problem';
export * from './formel';
export * from './loesung';
export * from './segment';
export * from './globalConfig';
export * from './config';
